
from flask import Flask, render_template, request
import fakeapi as api

app = Flask(__name__, static_url_path='', template_folder='./web/templates', static_folder='./web/static')


@app.route('/')
def ProfileTemplete():
    user = request.args.get('user')
    userProfile, RatingColor, RatingIcon = api.ReadUserProfile(user)
    return render_template('index.html',
                           Profile_Icon=userProfile.Badge,
                           Profile_Background=userProfile.Background,
                           Profile_Name=userProfile.DisplayName,
                           Profile_ShortID=userProfile.ShortID,
                           Profile_Level=userProfile.Level,
                           Profile_Rating=userProfile.Rating,
                           Rating_Img=RatingIcon,
                           Rating_Color=RatingColor,
                           Profile_Avatar=userProfile.Character,



                           Stat_I_Clear=userProfile.I_Stats[0],
                           Stat_I_FC=userProfile.I_Stats[1],
                           Stat_I_AP=userProfile.I_Stats[2],
                           Stat_II_Clear=userProfile.II_Stats[0],
                           Stat_II_FC=userProfile.II_Stats[1],
                           Stat_II_AP=userProfile.II_Stats[2],
                           Stat_III_Clear=userProfile.III_Stats[0],
                           Stat_III_FC=userProfile.III_Stats[1],
                           Stat_III_AP=userProfile.III_Stats[2],
                           Stat_IV_Clear=userProfile.IV_Stats[0],
                           Stat_IV_FC=userProfile.IV_Stats[1],
                           Stat_IV_AP=userProfile.IV_Stats[2],
                           Stat_IV_A_Clear="0",
                           Stat_IV_A_FC="0",
                           Stat_IV_A_AP="0",



                           b1_name = userProfile.Ratings[0].name,
                           b1_diff = userProfile.Ratings[0].level,
                           b1_score = userProfile.Ratings[0].score,
                           b1_orig_constant = userProfile.Ratings[0].chart_constant,
                           b1_rating = userProfile.Ratings[0].rating,
                           b2_name = userProfile.Ratings[1].name,
                           b2_diff = userProfile.Ratings[1].level,
                           b2_score = userProfile.Ratings[1].score,
                           b2_orig_constant = userProfile.Ratings[1].chart_constant,
                           b2_rating = userProfile.Ratings[1].rating,
                           b3_name = userProfile.Ratings[2].name,
                           b3_diff = userProfile.Ratings[2].level,
                           b3_score = userProfile.Ratings[2].score,
                           b3_orig_constant = userProfile.Ratings[2].chart_constant,
                           b3_rating = userProfile.Ratings[2].rating,
                           b4_name = userProfile.Ratings[3].name,
                           b4_diff = userProfile.Ratings[3].level,
                           b4_score = userProfile.Ratings[3].score,
                           b4_orig_constant = userProfile.Ratings[3].chart_constant,
                           b4_rating = userProfile.Ratings[3].rating,
                           b5_name = userProfile.Ratings[4].name,
                           b5_diff = userProfile.Ratings[4].level,
                           b5_score = userProfile.Ratings[4].score,
                           b5_orig_constant = userProfile.Ratings[4].chart_constant,
                           b5_rating = userProfile.Ratings[4].rating,
                           b6_name = userProfile.Ratings[5].name,
                           b6_diff = userProfile.Ratings[5].level,
                           b6_score = userProfile.Ratings[5].score,
                           b6_orig_constant = userProfile.Ratings[5].chart_constant,
                           b6_rating = userProfile.Ratings[5].rating,
                           b7_name = userProfile.Ratings[6].name,
                           b7_diff = userProfile.Ratings[6].level,
                           b7_score = userProfile.Ratings[6].score,
                           b7_orig_constant = userProfile.Ratings[6].chart_constant,
                           b7_rating = userProfile.Ratings[6].rating,
                           b8_name = userProfile.Ratings[7].name,
                           b8_diff = userProfile.Ratings[7].level,
                           b8_score = userProfile.Ratings[7].score,
                           b8_orig_constant = userProfile.Ratings[7].chart_constant,
                           b8_rating = userProfile.Ratings[7].rating,
                           b9_name = userProfile.Ratings[8].name,
                           b9_diff = userProfile.Ratings[8].level,
                           b9_score = userProfile.Ratings[8].score,
                           b9_orig_constant = userProfile.Ratings[8].chart_constant,
                           b9_rating = userProfile.Ratings[8].rating,
                           b10_name = userProfile.Ratings[9].name,
                           b10_diff = userProfile.Ratings[9].level,
                           b10_score = userProfile.Ratings[9].score,
                           b10_orig_constant = userProfile.Ratings[9].chart_constant,
                           b10_rating = userProfile.Ratings[9].rating,
                           b11_name = userProfile.Ratings[10].name,
                           b11_diff = userProfile.Ratings[10].level,
                           b11_score = userProfile.Ratings[10].score,
                           b11_orig_constant = userProfile.Ratings[10].chart_constant,
                           b11_rating = userProfile.Ratings[10].rating,
                           b12_name = userProfile.Ratings[11].name,
                           b12_diff = userProfile.Ratings[11].level,
                           b12_score = userProfile.Ratings[11].score,
                           b12_orig_constant = userProfile.Ratings[11].chart_constant,
                           b12_rating = userProfile.Ratings[11].rating,
                           b13_name = userProfile.Ratings[12].name,
                           b13_diff = userProfile.Ratings[12].level,
                           b13_score = userProfile.Ratings[12].score,
                           b13_orig_constant = userProfile.Ratings[12].chart_constant,
                           b13_rating = userProfile.Ratings[12].rating,
                           b14_name = userProfile.Ratings[13].name,
                           b14_diff = userProfile.Ratings[13].level,
                           b14_score = userProfile.Ratings[13].score,
                           b14_orig_constant = userProfile.Ratings[13].chart_constant,
                           b14_rating = userProfile.Ratings[13].rating,
                           b15_name = userProfile.Ratings[14].name,
                           b15_diff = userProfile.Ratings[14].level,
                           b15_score = userProfile.Ratings[14].score,
                           b15_orig_constant = userProfile.Ratings[14].chart_constant,
                           b15_rating = userProfile.Ratings[14].rating,
                           b16_name = userProfile.Ratings[15].name,
                           b16_diff = userProfile.Ratings[15].level,
                           b16_score = userProfile.Ratings[15].score,
                           b16_orig_constant = userProfile.Ratings[15].chart_constant,
                           b16_rating = userProfile.Ratings[15].rating,
                           b17_name = userProfile.Ratings[16].name,
                           b17_diff = userProfile.Ratings[16].level,
                           b17_score = userProfile.Ratings[16].score,
                           b17_orig_constant = userProfile.Ratings[16].chart_constant,
                           b17_rating = userProfile.Ratings[16].rating,
                           b18_name = userProfile.Ratings[17].name,
                           b18_diff = userProfile.Ratings[17].level,
                           b18_score = userProfile.Ratings[17].score,
                           b18_orig_constant = userProfile.Ratings[17].chart_constant,
                           b18_rating = userProfile.Ratings[17].rating,
                           b19_name = userProfile.Ratings[18].name,
                           b19_diff = userProfile.Ratings[18].level,
                           b19_score = userProfile.Ratings[18].score,
                           b19_orig_constant = userProfile.Ratings[18].chart_constant,
                           b19_rating = userProfile.Ratings[18].rating,
                           b20_name = userProfile.Ratings[19].name,
                           b20_diff = userProfile.Ratings[19].level,
                           b20_score = userProfile.Ratings[19].score,
                           b20_orig_constant = userProfile.Ratings[19].chart_constant,
                           b20_rating = userProfile.Ratings[19].rating,
                           b21_name = userProfile.Ratings[20].name,
                           b21_diff = userProfile.Ratings[20].level,
                           b21_score = userProfile.Ratings[20].score,
                           b21_orig_constant = userProfile.Ratings[20].chart_constant,
                           b21_rating = userProfile.Ratings[20].rating,
                           b22_name = userProfile.Ratings[21].name,
                           b22_diff = userProfile.Ratings[21].level,
                           b22_score = userProfile.Ratings[21].score,
                           b22_orig_constant = userProfile.Ratings[21].chart_constant,
                           b22_rating = userProfile.Ratings[21].rating,
                           b23_name = userProfile.Ratings[22].name,
                           b23_diff = userProfile.Ratings[22].level,
                           b23_score = userProfile.Ratings[22].score,
                           b23_orig_constant = userProfile.Ratings[22].chart_constant,
                           b23_rating = userProfile.Ratings[22].rating,
                           b24_name = userProfile.Ratings[23].name,
                           b24_diff = userProfile.Ratings[23].level,
                           b24_score = userProfile.Ratings[23].score,
                           b24_orig_constant = userProfile.Ratings[23].chart_constant,
                           b24_rating = userProfile.Ratings[23].rating,
                           b25_name = userProfile.Ratings[24].name,
                           b25_diff = userProfile.Ratings[24].level,
                           b25_score = userProfile.Ratings[24].score,
                           b25_orig_constant = userProfile.Ratings[24].chart_constant,
                           b25_rating = userProfile.Ratings[24].rating,
                           b26_name = userProfile.Ratings[25].name,
                           b26_diff = userProfile.Ratings[25].level,
                           b26_score = userProfile.Ratings[25].score,
                           b26_orig_constant = userProfile.Ratings[25].chart_constant,
                           b26_rating = userProfile.Ratings[25].rating,
                           b27_name = userProfile.Ratings[26].name,
                           b27_diff = userProfile.Ratings[26].level,
                           b27_score = userProfile.Ratings[26].score,
                           b27_orig_constant = userProfile.Ratings[26].chart_constant,
                           b27_rating = userProfile.Ratings[26].rating,
                           b28_name = userProfile.Ratings[27].name,
                           b28_diff = userProfile.Ratings[27].level,
                           b28_score = userProfile.Ratings[27].score,
                           b28_orig_constant = userProfile.Ratings[27].chart_constant,
                           b28_rating = userProfile.Ratings[27].rating,
                           b29_name = userProfile.Ratings[28].name,
                           b29_diff = userProfile.Ratings[28].level,
                           b29_score = userProfile.Ratings[28].score,
                           b29_orig_constant = userProfile.Ratings[28].chart_constant,
                           b29_rating = userProfile.Ratings[28].rating,
                           b30_name = userProfile.Ratings[29].name,
                           b30_diff = userProfile.Ratings[29].level,
                           b30_score = userProfile.Ratings[29].score,
                           b30_orig_constant = userProfile.Ratings[29].chart_constant,
                           b30_rating = userProfile.Ratings[29].rating
                           )
    
def startflask():
    app.run()